name: Run AnimaTween Package Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  UNITY_VERSION: 2022.3.10f1

jobs:
  test:
    name: Run UPM Package Tests 📦
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rename Tests folder
        run: mv Tests~ Tests

      - name: Create empty Unity test project
        run: |
          mkdir test-project
          mkdir test-project/Assets
          mkdir test-project/Packages
          mkdir test-project/ProjectSettings
          echo '{ "dependencies": { "com.esdrascaleb.animatween": "file:../" } }' > test-project/Packages/manifest.json
          echo "projectVersion: ${UNITY_VERSION}" > test-project/ProjectSettings/ProjectVersion.txt

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: test-project/Library
          key: Library-${{ hashFiles('Packages/packages-lock.json') }}
          restore-keys: |
            Library-

      - name: Run Unity tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: test-project
          unityVersion: ${{ env.UNITY_VERSION }}
          testMode: all

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test results (all modes)
          path: test-project/test-results